// <auto-generated />
using System;
using MOHEswatini.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MOHEswatini.Migrations
{
    [DbContext(typeof(DbMOHEswatini))]
    [Migration("20200617085948_MOHEswatiniMigration")]
    partial class MOHEswatiniMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MOHEswatini.Models.mDiseaseSurveillance", b =>
                {
                    b.Property<int>("iID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnName("cAge")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnName("dArrivalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ArrivedBy")
                        .IsRequired()
                        .HasColumnName("cArrivedBy")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Bleeding")
                        .HasColumnName("lBleeding")
                        .HasColumnType("bit");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnName("cContactNo")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("Cough")
                        .HasColumnName("lCough")
                        .HasColumnType("bit");

                    b.Property<string>("CountryOfResidence")
                        .IsRequired()
                        .HasColumnName("cCountryOfResidence")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CovidTestResult")
                        .HasColumnName("cCovidTestResult")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("CovidTested")
                        .HasColumnName("lCovidTested")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CovidTestingDate")
                        .HasColumnName("dCovidTestingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CovidTestingKitNo")
                        .HasColumnName("cCovidTestingKitNo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CovidTestingLab")
                        .HasColumnName("cCovidTestingLab")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("Diarrhea")
                        .HasColumnName("lDiarrhea")
                        .HasColumnType("bit");

                    b.Property<bool>("Fever")
                        .HasColumnName("lFever")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnName("cGender")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("GeneralBodyPain")
                        .HasColumnName("lGeneralBodyPain")
                        .HasColumnType("bit");

                    b.Property<bool>("Headache")
                        .HasColumnName("lHeadache")
                        .HasColumnType("bit");

                    b.Property<string>("HealthFacility")
                        .HasColumnName("cHealthFacility")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("Malaria")
                        .HasColumnName("lMalaria")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("cName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("NoOfDaysSpend1")
                        .HasColumnName("cNoOfDaysSpend1")
                        .HasColumnType("int");

                    b.Property<int>("NoOfDaysSpend13")
                        .HasColumnName("cNoOfDaysSpend3")
                        .HasColumnType("int");

                    b.Property<int>("NoOfDaysSpend2")
                        .HasColumnName("cNoOfDaysSpend2")
                        .HasColumnType("int");

                    b.Property<int>("NoOfDaysSpend4")
                        .HasColumnName("cNoOfDaysSpend4")
                        .HasColumnType("int");

                    b.Property<bool>("Others")
                        .HasColumnName("lOthers")
                        .HasColumnType("bit");

                    b.Property<string>("OthersVaccine")
                        .HasColumnName("cOthersVaccine")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("PassportNo")
                        .IsRequired()
                        .HasColumnName("cPassportNo")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasColumnName("cPhysicalAddress")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("PhysicalContactNo")
                        .IsRequired()
                        .HasColumnName("cPhysicalContactNo")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("PointOfEntry")
                        .IsRequired()
                        .HasColumnName("cPointOfEntry")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("Polio")
                        .HasColumnName("lPolio")
                        .HasColumnType("bit");

                    b.Property<string>("RecentlyVisitedCountry1")
                        .IsRequired()
                        .HasColumnName("cRecentlyVisitedCountry1")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("RecentlyVisitedCountry2")
                        .IsRequired()
                        .HasColumnName("cRecentlyVisitedCountry2")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("RecentlyVisitedCountry3")
                        .IsRequired()
                        .HasColumnName("cRecentlyVisitedCountry3")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("RecentlyVisitedCountry4")
                        .IsRequired()
                        .HasColumnName("cRecentlyVisitedCountry4")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("SeatNo")
                        .HasColumnName("cSeatNo")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("SoreThroat")
                        .HasColumnName("lSoreThroat")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnName("cVehicleNo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Vomiting")
                        .HasColumnName("lVomiting")
                        .HasColumnType("bit");

                    b.Property<bool>("YellowFever")
                        .HasColumnName("lYellowFever")
                        .HasColumnType("bit");

                    b.HasKey("iID");

                    b.ToTable("T_DiseaseSurveillance");
                });

            modelBuilder.Entity("MOHEswatini.Models.mLogin", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnName("cUserID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EmailID")
                        .HasColumnName("cEmailID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasColumnName("cName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("cPassword")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasColumnName("cContactNo")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("Type")
                        .HasColumnName("cUserType")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("UserID");

                    b.ToTable("U_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
